### ISSUE TITLE
Add a button/link that lets you easily file issues on the website repo

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/paketo-website#104]
## What happened?

* What were you attempting to do?

I saw a typo on a Paketo docs page and I wanted to quickly open an issue or pull request calling out the problem.

* What did you expect to happen?
I expected to see

a) an "edit" button that would drop me into the Github UI for proposing an edit to the page (e.g. https://github.com/paketo-buildpacks/paketo-website/edit/main/content/docs/builders/_index.md), and/or

b) a link/button that brings me to the [Paketo site issues](https://github.com/paketo-buildpacks/paketo-website/issues) so I can easily file an issue re: the docs.

* What was the actual behavior? Please provide log output, if possible.
I had to figure out where the site lives in Github, dig through the markdown files for the one where I saw the error, and then open an issue with my suggestion.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by fg-j** [comment]
For example, https://docs.tilt.dev/ has an "Edit on Github" button on all their docs pages that drops you into the Github view of the given page.

**Comment by sophiewigmore** [comment]
+1 idea

**Comment by kvedurmu** [comment]
Just to clarify @fg-j, you're proposing that we add a "github" button at the bottom of every docs page that takes the user directly to the specific docs page? If so, 100% agree that we should do this 😀

**Comment by fg-j** [comment]
@kvedurmu exactly. For example, the button on [the docs page about Builders](https://paketo.io/docs/builders/) would lead you to [this Github location](https://github.com/paketo-buildpacks/paketo-website/edit/main/content/docs/builders/_index.md).
