### ISSUE TITLE
All buildpack registry references should be updated from GCR to Dockerhub

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/paketo-website#120]
## What happened?
We've recently started publishing all Paketo Buildpac artifacts to Dockerhub in addition to GCR. We should update all existing documentation to reference the Dockerhub locations so that we can eventually move over to Dockerhub completely.

**Comment by fg-j** [comment]
@paketo-buildpacks/steering-committee Are we still intending to move entirely off of GCR, eventually?

**Comment by ryanmoran** [comment]
Yes. We should figure out where all the places are that we still reference GCR and move to Dockerhub.

**Comment by dmikusa-pivotal** [comment]
@paketo-buildpacks/java-buildpacks is probably the main culprit here. This has been on our TODO list for a long time but keeps getting bumped for other things.

What is the plan when we do stop publishing to GCR? Are we still going to maintain the old versions published to GCR? or are those going to be purged? Wondering if we need to do a migration of past versions to Docker so there is history on Docker?

**Comment by ryanmoran** [comment]
We should take a look at what is available on GCR that is not also available on Dockerhub. I think we've been publishing to both places for so long now that I would be really worried if there were users still using stuff that was only ever available on GCR.

**Comment by dmikusa-pivotal** [comment]
I have been meaning to submit an RFC for this, but I think we should have a retention policy for images. To dictate how long we retain them. IMHO, there is a finite lifetime where images are safe to be used and remain functional so we don't need to store them forever. I think it'd be nice to have a policy about this so we can safely prune old images.

**Comment by fg-j** [comment]
Now, we only mention GCR on the website when enumerating the URIs of our stack run images. Builder and buildpack GCR references have been swapped to Dockerhub or Buildpack Registry references.
