### ISSUE TITLE
ERROR: failed to read buildpack order file: open /buildpacks/order.toml: no such file or directory

### ISSUE THREAD

**Issue by pingyangtiaer** [paketo-buildpacks/paketo-website#130]
## What happened?

* What were you attempting to do?
to run the example that on this page https://paketo.io/docs/
* What did you expect to happen?
should be able to build the docker image and run
* What was the actual behavior? Please provide log output, if possible.
ERROR: failed to read buildpack order file: open /buildpacks/order.toml: no such file or directory
## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
MacOS
* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
I run _brew install buildpacks/tap/pack_ and add _. $(pack completion)_ to the .bashrc and .bash_profile:
* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by fg-j** [comment]
Hi there. 

Can you provide 
1. the exact commands that you ran and
2. the complete build log output and
3. The output of `pack version`? 

That'll give us a lot more context. The example I see on the docs page you linked is:
```
git clone https://github.com/paketo-buildpacks/samples
cd samples/demo-apps/app-source
pack build paketo-demo-app --builder paketobuildpacks/builder:base
```
I just tried it now using `pack ` version `0.18.0+git-e00ee4a.build-2328` and saw the app build successfully.

**Comment by pingyangtiaer** [comment]
cd samples
cd demo-apps/app-source
pack build paket-demo-app --builder paketobuildpacks/builder:base

I got:
➜  app-source git:(main) pack build paketo-demo-app --builder paketobuildpacks/builder:base
Pulling image index.docker.io/paketobuildpacks/builder:base
base: Pulling from paketobuildpacks/builder
e2cf0b38ebfc: Already exists 
79742e92f112: Already exists 
2cc711fadbef: Already exists 
dd4325c4bcfa: Already exists 
ad89b2951c65: Already exists 
817694fec55f: Already exists 
145272d4675f: Already exists 
357fefdf9bc9: Already exists 
df2a11ebcd38: Pulling fs layer 
2976c9dbeb66: Pulling fs layer 
962d8c81454b: Pulling fs layer 
54908e6fe9d2: Waiting 
a515d9d50f61: Waiting 
8151954a9698: Waiting 
cbbae9d68f35: Waiting 
282602fc640a: Waiting 
b0d6dff0baed: Waiting 
102b9c4578c7: Waiting 
4ca22103a370: Waiting 
8a9c31e8b757: Waiting 
1ad898d8bf0f: Waiting 
9dcd61a253ef: Waiting 
810567d695ce: Waiting 
df61ba6504cf: Waiting 
decade352b18: Waiting 
b935ba5fed8b: Waiting 
a94393801599: Pulling fs layer 
88d16ca07b74: Waiting 
d9312c9a3c52: Waiting 
862834ce0af4: Pulling fs layer 
1421d4b9c318: Waiting 
4a8f9381f1c4: Pull complete 
56d7bcca752e: Pull complete 
d1132d93a2b9: Pull complete 
be5310d8b8c2: Pull complete 
858dfe120bf2: Pull complete 
fa494bae78c2: Pull complete 
35e3ed76cf64: Pull complete 
aad2b408f3c7: Pull complete 
53487c094d2a: Pull complete 
52eaf46d6250: Pull complete 
b9bf72658c9f: Pull complete 
92d0e9cff007: Pull complete 
33d5ad1d909e: Pull complete 
09474fe777cd: Pull complete 
130f6ca3220b: Pull complete 
e838f96325c0: Pull complete 
b59e432c3466: Pull complete 
1db4b9335a68: Pull complete 
c472a784c4df: Pull complete 
0c3e4cca3d4a: Pull complete 
64ff4f6b6dfb: Pull complete 
276104402bec: Pull complete 
49fff256768c: Pull complete 
593da7c147c9: Pull complete 
2ae2cd21a639: Pull complete 
481ab150c792: Pull complete 
f2c1138c16bb: Pull complete 
62677e279a12: Pull complete 
51c5c6f90192: Pull complete 
4f725112e41a: Pull complete 
a1b8e260a955: Pull complete 
d05bec81f444: Pull complete 
20f21476d9f9: Pull complete 
dffc3649d0ab: Pull complete 
f17b2504fe3f: Pull complete 
72ad9888618d: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:e848fd59e8f39231d231c347970bd7e5544246cb70b356d4757bed8b48bb0643
Status: Downloaded newer image for paketobuildpacks/builder:base
Selected run image index.docker.io/paketobuildpacks/run:base-cnb from builder
Pulling image index.docker.io/paketobuildpacks/run:base-cnb
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:0bf521429c5fac06616ef542da735f9e34c4997cc5d5987242eb7199b04ac923
Status: Image is up to date for paketobuildpacks/run:base-cnb
Using build cache volume pack-cache-ae2f45609969.build
Executing lifecycle version 0.11.1

pack version
v0.2.1 (git sha: 61ee7f03562cdb46c7bab773f7bf58c89d73f30b)

**Comment by fg-j** [comment]
Holy cow! It looks like you're running a *very* old version of `pack`. I highly recommend you upgrade to the latest version (using their [installation instructions](https://buildpacks.io/docs/tools/pack/)). If `brew install buildpacks/tap/pack` is still resulting in version 0.2.1, I advise you follow the manual installation instructions.

**Comment by kvedurmu** [comment]
I'm going to close this out. Feel free to reopen if you're still seeing this error after upgrading `pack` to a newer version.
