### ISSUE TITLE
Self-nomination as content subteam contributor

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#156]
In keeping with the [Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I am self-nominating as a contributor to the content subteam.

I will be working with @fg-j as part of the website redesign initiative and have, in the past, contributed documentation updates.

**Comment by fg-j** [comment]
I approve this nomination! @kvedurmu or @ForestEckhardt , can I get a +1?

**Comment by ForestEckhardt** [comment]
@fg-j I believe @kvedurmu is an emeritus maintainer so you are good to move on.

**Comment by ryanmoran** [comment]
@andymoe has been added to the Content Contributor team and has those permissions. This can be closed.
