### ISSUE TITLE
Redesign mobile homepage per Figma

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#158]
# Summary
First pass of mobile homepage redesign per [figma](https://www.figma.com/file/vc91zvGMqGxY022FUoOm4S/Paketo_Web_0.01?node-id=57%3A34) and [Zeplin](https://app.zeplin.io/project/609929b9d9f48f3a6e223971/dashboard)

# A/C
`AS` a User on a mobile device
`WHEN` I visit the homepage of the [staging site](https://paketo-staging.web.app/)
`THEN` It matches the Figma mobile designs
`AND` contains a keyshape animation in the "How It works" section.

# Remaining To-dos

- [x] Address logo sizing on homepage (may need individual sizing)
~- [ ] Parameterize content of features list(s) rather than inlining text in HTML directly~ Will be split into separate issue
- [x] Get Started button opacity change on hover
- [x] Fix weird stretching of Jenkins, CircleCI, and AzureDevOps logos
- [x] Give dark-background sections drop-shadows
- [x] Make nav hamburger expansion fill the whole screen (see Figma)
~- [ ] Improve footer social media linking for accessibility (Twitter, Slack Github)~ Will be split into separate issue
- [x] Get SVG for CloudFoundry logo instead of PNG. (Convert from EPS found [here](https://www.cloudfoundry.org/logo/)?)
- [x] Figure out alternative to Metropolis font for footer (which isn't supported in some browsers?)

Open questions:
- Does nav hamburger // docs menu tray (mobile) follow as you scroll? (Moved to https://github.com/paketo-buildpacks/paketo-website/issues/165)
- Does expanded nav menu on mobile fill entire screen? (Yes, but text layout needs improved see https://github.com/paketo-buildpacks/paketo-website/issues/166)
- Correct Privacy Policy link?(what is the correct destination? ) - *Our link is correct*

**Comment by fg-j** [comment]
@kvedurmu I sort of like how the expanded hamburger fills the whole screen. I have the smallest iPhone, and when I look at a site like Divio on mobile, the side navigation tray feels too-small and unfriendly.

**Comment by kvedurmu** [comment]
Oh that's interesting. I get why the whole screen could make sense now. The Figma help site kinda does what you're describing, where expanding the hamburger fills the whole screen horizontally. Vertically, once the the menu options end it just shows the page content underneath, which looks pretty nice.
![image](https://user-images.githubusercontent.com/37810054/121592771-21789880-ca09-11eb-80b1-682c696f00af.png)

**Comment by ryanmoran** [comment]
For the hovering hamburger button, it looks like it is really the whole page header on the Divio site that follows you as you scroll.

![Screen Shot 2021-06-11 at 10 27 13 AM](https://user-images.githubusercontent.com/155736/121726760-d65d9480-ca9f-11eb-98ba-130e3153a513.png)

It kinda bugs me that right now its just the three lines of the hamburger that follow you. I find it distracting how those lines interplay with text and images as they overlap on smaller screens.

**Comment by fg-j** [comment]
Maybe it would look nice if something sort of like this followed you down the page:
![Screen Shot 2021-06-11 at 1 53 12 PM](https://user-images.githubusercontent.com/21328286/121729519-9527ad80-cabc-11eb-8138-e3b561e03d7b.png)

(except with better alignment/relative sizing)

**Comment by andymoe** [comment]
Split out the remaining issues around the floating nav and feedback around text layout on expanded mobile menu on separate issues:

- https://github.com/paketo-buildpacks/paketo-website/issues/165
- https://github.com/paketo-buildpacks/paketo-website/issues/166

Closing this issue.
