### ISSUE TITLE
An iPhone User with a notch on their phone has a good visual experience in portrait mode

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#163]
# Summary
As and iPhone user with a later model that sports a "notch" cutout  for Face ID hardware should have a good visual experience when visiting the site in portrait mode.

# A/C
`GIVEN` I visits the website on an iPhone with a `Notch`
`WHEN` I my phone is in portrait mode
`THEN` the sites background color reaches edge-to-edge
`AND` no content is hidden by the `Notch` as I scroll.

## Resources
https://css-tricks.com/the-notch-and-css

**Comment by fg-j** [comment]
This was resolved in #296
