### ISSUE TITLE
Theme existing docs and community pages to match new design for phase 1 release

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#164]
## Summary
We'd like to release the updated homepage as part of PHASE1 so that we can get additional feedback and don't have to wait for all parts of the site to be rebuilt to release and in order to feel comfortable doing the `docs` and `community` pages should somewhat match the new design.

Remaining fixes

- [x] Nav menu no longer fills the whole screen on mobile
- [x] correct Paketo logo placement/size on non-homepage
- [x] ensure expanded nav menu links are identical on homepage and other pages
- [x] Use new theme colors and fonts for docs and community pages
- [x] Prevent docs content width from expanding wider than the header width

**Comment by andymoe** [comment]
forgot to add issue id to this commit: https://github.com/paketo-buildpacks/paketo-website/commit/096b63e6cdd2c189231711104785e2eb646d7abe

**Comment by fg-j** [comment]
Remaining fixes

- [ ] Nav menu no longer fills the whole screen on mobile
- [ ] correct Paketo logo placement/size on non-homepage
- [ ] ensure expanded nav menu links are identical on homepage and other pages
