### ISSUE TITLE
Determine what to do about floating hamburger menu on mobile. 

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#165]
The floating hamburger interaction is not well loved by all. 

See discussion here: https://github.com/paketo-buildpacks/paketo-website/issues/158#issuecomment-858970547

**Comment by andymoe** [comment]
Let's get some input from the designer and perhaps write down some pro's/cons of proposed solutions. (sticky nav bar vs fixed hamburger vs leave as is?)

**Comment by mhagan-vm** [comment]
Hi Andy, I envisioned the hamburger to stick to float in the top right corner of the screen and remain visible no matter which way the user scrolls. I realize that this means there are some times when it sits nicely in the layout of the content and other times when it casually sits right on top of some content, which doesn't look great. Maybe we can add a transparent shape behind the hamburger but on top of the content to maintain some separation? I usually try to avoid a horizontal nav going all the way across, especially one that shows and hides depending on scroll direction, but that is just my preference, I'm open to other ideas. 

As for the "...", this was inspired by https://help.figma.com/hc/en-us/articles/360040531773-Share-or-embed-your-files-and-prototypes
If you go to that link and make your browser window as narrow as possible you'll see what I'm talking about. Again, I'm open other ideas. It's your site so I want you to like it! :)

**Comment by fg-j** [comment]
Given that it's been about a year since there was last activity on this issue, I'm closing for now. If people have significant concerns about the current hamburger menu, please reopen.
