### ISSUE TITLE
Improve text layout of expanded nav menu on Mobile.

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#166]
## Summary
Right now the fully expanded nav menu covers the screen on mobile however the text spacing and interaction feels off.
**A/C**
Sort out a layout that feels better space wise. Engage the designer for opinions/feedback/help on this.

![Screen Shot 2021-06-14 at 10 42 26 PM](https://user-images.githubusercontent.com/10627/121999229-e4dad300-cd61-11eb-9eeb-8aacc53e0ad6.png)

**Comment by andymoe** [comment]
Basically it's hard to reach the bottom links on something the size of and iPhone X or iPhone 12. Perhaps we can squish them together somehow.

**Comment by fg-j** [comment]
This is quite stale. If someone else complains, we'll think about addressing it!
