### ISSUE TITLE
Add additional logos to homepage

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#169]
Add the following additional logos (Is it too many logos?) under last paragraph of "what are buildpacks?" sections.

-  Hashicorp Waypoint
- Pack CLI
- Spring Boot
- Tilt
- VMware Tanzu Build Service.

**Comment by fg-j** [comment]
Blocked pending finalization of the mockup. Which logos do we actually want, how do we want them arranged? Possibly a question for @kvedurmu.

**Comment by fg-j** [comment]
Potentially this is a question for @mvalliath now?

**Comment by mvalliath** [comment]
I don't context on why these five platforms were chosen in particular to feature.

Best move is to probably add all five for now.
