### ISSUE TITLE
Re-organize doc markdown and nav according to new design's information architecture

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#186]
## Summary
Update doc organization so the top level items are:
- Get Started
- How to
- Reference
- Concepts

**Notes:** 
- Existing links should not be broken but rather forwarded to pages that have moved or redirected to replacement pages.
- In the new design the `How to`, `Reference` and `Concepts' sections don't have their own landing pages.

**Comment by fg-j** [comment]
The Hugo concept of [aliases](https://gohugo.io/content-management/urls/#example-aliases) can help us achieve redirecting links.
