### ISSUE TITLE
Ensure new docs nav works well on desktop

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#187]
## Summary
Since we are going to be working "mobile first" but also want to ship incrementally we need to make sure the changes we have made when reorganizing the nav for the docs functions well on desktop browsers. 

**Note**: This is a blocker for deploying phase 2.

**Comment by fg-j** [comment]
Blocked until #201 is completed.

**Comment by fg-j** [comment]
Adding this condition as an acceptance criterion of #201. Closing.
