### ISSUE TITLE
Add skip links to top and bottom of site pages

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/paketo-website#195]
[Skip links](http://web-accessibility.carnegiemuseums.org/code/skip-link/) are links that allow a user to skip past headers and sidebars to the main content of a page. The improve a site's accessibility for users navigating with switches and keyboard controls because they help avoid the fatigue of tabbing past repetitive content. The site should include skip links at the top of each `<body>` that skip past navs to the main page content and at the end of main page content that skip back to the top of the content.

## A/C
`AS` a user navigating the Paketo site by tabbing through focusable elements
`WHEN` I press `TAB` for the first time on any page on the site
`THEN` A skip link should appear onscreen, and be focused
`AND` When I use the link, the page focus should skip to the main content of the page

AND

`AS` a user navigating the Paketo site by tabbing through focusable elements
`WHEN` I have focused the last focusable element of the page's main content and I tab again
`THEN` `THEN` A skip link should appear onscreen, and be focused
`AND` When I use the link, the page focus should skip to the skip link at the top of the page

AND

`AS` a user navigating the Paketo site using a mouse
`WHEN` I interact with any page on the site without using keyboard controls
`THEN` I should not see any skip links on the page

**Comment by andymoe** [comment]
Had to revert the PR because it broke the bookmark links: https://github.com/paketo-buildpacks/paketo-website/pull/238

I've not yet investigated what in particular broke all the links. There appears to have been some reformatting of the code that generates them which was suspect but again i don't actually know yet.
