### ISSUE TITLE
Consider adding a containing div with max-width property for header and footer

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#197]
## Summary
Right now when you make the browser full screen on a widescreen or large monitor the nav and logos on the header and footer on desktops are all the way to the right and left of the screen respectively. Because all content on the homepage is centered and narrower we should consider containing how far to the edge of the screen header and footer elements should be allowed to move.

**Comment by fg-j** [comment]
This is quite stale. If someone else complains, we'll think about addressing it!

**Comment by andymoe** [comment]
😭
