### ISSUE TITLE
Show/hide docs navigation tray

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/paketo-website#201]
On mobile, the current docs layout places the navigation menu above the page content. This means that users have to see and scroll past the entire menu before arriving at each documentation page. In the [Figma mockup](https://www.figma.com/file/vc91zvGMqGxY022FUoOm4S/Paketo_Web_0.01?node-id=189%3A350) the navigation is shown in a show/hide-able tray (see images). The existing navigation bar should be placed in an interactive nav tray to improve the mobile UX.

## A/C
`AS` a user on the Paketo docs site on a mobile device
`WHEN` I initially load any page on the docs site
`THEN` the docs navigation menu is hidden
`AND` I can tap on the opener to reveal/hide the navigation pane

`AS` a user on the Paketo docs site on desktop
`WHEN` I visit any page on the docs site
`THEN` The docs navigation is in a lefthand sidebar and always visible

![image](https://user-images.githubusercontent.com/21328286/124641914-348e5500-de5d-11eb-8636-3a3cd299da3b.png)
![image](https://user-images.githubusercontent.com/21328286/124641951-3e17bd00-de5d-11eb-97ed-e81dadbd2322.png)

**Comment by simonjjones** [comment]
Blocking to ensure this isn't worked on in parallel with https://github.com/paketo-buildpacks/paketo-website/issues/263
