### ISSUE TITLE
Create a website Contribute page

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/paketo-website#21]
We should create a new "Contribute" page on the website so that we can better surface content around the project and community so that it's easy for new contributors to get started with the project.

There's probably a lot we can add here, but a first pass it would be good to have the following information surfaced:
- Browse issues or file an issue
- How to contribute:
     - write and link a contributing guide
     - read about governance/other RFCs
     - try to fix good first issues
     - help out on open issues
     - join in on discussion issues
- Join working groups
- Join slack
- Help improve docs

example contributing guide - https://github.com/envoyproxy/envoy/blob/master/CONTRIBUTING.md

**Comment by sophiewigmore** [comment]
https://github.com/paketo-buildpacks/.github/blob/main/CONTRIBUTING.md this doc could have helpful resources for this issue
