### ISSUE TITLE
Move staging site to firebase hosting on paketo gcp

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/paketo-website#243]
## Summary
We need to move our staging site to firebase hosting on the `paketo-buildpacks` GCP account.

## Details
We will need new firebase "Hosting" site set up called paketo-staging (may need a different name initially since that is used in other account)

We will also need a gcp service account create with the following roles:

- `roles/firebasehosting.admin` (Firebase Hosting Admin)
- `roles/serviceusage.apiKeysViewer` (API Keys Viewer)

(Be sure to download the service-account-file.json when creating the account)

Finally, we will need to log into the firebase cli using the service account by using something like this:
`export GOOGLE_APPLICATION_CREDENTIALS="/home/user/Downloads/service-account-file.json"` (https://cloud.google.com/docs/authentication/production#linux-or-macos)

 - Needed changed to configure `GOOGLE_APPLICATION_CREDENTIALS` are in this PR https://github.com/paketo-buildpacks/paketo-website/pull/248
 
Once tested (GHA currently down on Aug 10th) the following changes need to be made:

- [x] Update the following secretes for this repo: `GCP_PROJECT_ID` and `GCP_SA_KEY` (The json key from the GCP service account)
- [x] Ensure new "Hosting" site is set up under firebase
- [x] If the new site name differs from the old one then update then replace `paketo-staging` with the new site name in the following lines of code: https://github.com/paketo-buildpacks/paketo-website/blob/main/deploy.js#L13-L16
- [x] Update `.firebaserc` file https://github.com/paketo-buildpacks/paketo-website/blob/main/.firebaserc with the new GCP account name.

**Comment by fg-j** [comment]
I think we can use the Google official `setup-gcloud` [Github action](https://github.com/google-github-actions/setup-gcloud) with the `export_default_credentials` to expose the `GOOGLE_APPLICATION_CREDENTIALS` environment variable for the firebase deploy step in our workflows.

**Comment by fg-j** [comment]
It seems like automated PR deploys are currently failing for a permissions reason:
https://github.com/paketo-buildpacks/paketo-website/pull/254/checks?check_run_id=3308538680#step:9:16

**Comment by fg-j** [comment]
Deploys are now working!
