### ISSUE TITLE
Create Getting Started guide for .NET Core developers

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/paketo-website#245]
The current [Getting started](https://paketo.io/docs/) page only includes one example, and it's a Node.js app. Many Paketo buildpacks users are .NET developers

We should have a getting started guide targeted toward .NET developers.

The new guide should:

- [ ] Link to a cloneable, runnable sample app that lives in the Paketo samples repo
- [ ] Be in its own h2 section on the current Getting Started page
- [ ] Include copyable code snippets for relevant actions the developer needs to take
- [ ] Use the pack CLI as the build platform

**Comment by qayshp** [comment]
Not saying it's perfect, but there is a page for dotNET Core
https://github.com/paketo-buildpacks/paketo-website/blob/3e608b2516e6224b487ee18da8e39848102da2a8/content/docs/howto/dotnet-core.md ?

**Comment by qayshp** [comment]
sorry, to clarify, I'm having a [problem](https://github.com/paketo-buildpacks/samples/issues/146) following that guide, so it definitely isn't perfect, which is why I've been searching through issues.

**Comment by qayshp** [comment]
Ok, having read more of the issues/commits in this project, I feel like my first post was inappropriate 🤭.
I must have misunderstood what you meant, and I'm sorry I jumped in here linking to that page 😬. I will delete all of my comments here if that would be better.

**Comment by fg-j** [comment]
We've definitely got some content on the site already that can serve as a "Getting Started" for .NET devs. We just want to surface that more clearly -- and spiff up those docs, as well.
