### ISSUE TITLE
Interactive Calendar Widget for Community Page

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/paketo-website#261]
The [mockup](https://www.figma.com/file/vc91zvGMqGxY022FUoOm4S/Paketo_Web_0.01?node-id=475%3A2149) of the redesigned community page shows an interactive widget that shows when the next Paketo meetings are:

![image](https://user-images.githubusercontent.com/21328286/129602787-24e0ae4e-e2a9-463c-8a6e-1d873998769e.png)

The CNB [community page](https://buildpacks.io/community/) already includes such a widget.

This issue is to find out what service the CNB site uses for this calendar and add one to the Paketo site.

**Comment by simonjjones** [comment]
This seems to be backed by the website teamup.com

**Comment by ryanmoran** [comment]
Here is the shortcode used on `buildpacks.io`: https://github.com/buildpacks/docs/blob/f66a95f5befd21594effe7ac6ea244f0af783262/themes/buildpacks/layouts/shortcodes/calendar.html

**Comment by simonjjones** [comment]
Let's also follow the request in #263 

> Currently, the layout of the community page has the section about the Working Group Meeting a the bottom of the page. I think that is would be better if that sections was moved closer to the top to ensure that newcomers see our WG meeting. I think something similar to the buildpacks.io/community would be ideal.

**Comment by fg-j** [comment]
Closing since we currently only host one community event per week. We can revisit this if we've got more meetings to display on a calendar.
