### ISSUE TITLE
Rearrange community page

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/paketo-website#268]
Currently, the layout of the community page has the section about the Working Group Meeting a the bottom of the page. I think that is would be better if that sections was moved closer to the top to ensure that newcomers see our WG meeting. I think something similar to the [buildpacks.io/community](buildpacks.io/community) would be ideal.

**Comment by simonjjones** [comment]
Let's make these changes as part of https://github.com/paketo-buildpacks/paketo-website/issues/261 where we'll be adding a calendar widget with working group events. I'll gather this context into that issue and close this for now.
