### ISSUE TITLE
Fix Redesigned hero section to be mobile responsive

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/paketo-website#33]
We recently made some changes to update the website hero section to surface builder locations and also move the language family logos to the bottom of the hero section (see https://github.com/paketo-buildpacks/paketo-website/issues/28). These changes do a great job communicating what the Paketo project produces and which languages are supported in each builder, but doesn't render too well on mobile resolutions.

![image](https://user-images.githubusercontent.com/37810054/90646656-742c5e00-e205-11ea-9cbe-97137bfcc8ca.png)

To make this mobile responsive, we could either:
1) ~~Get rid of the tabs (for Full, Base, Tiny), simply display **all** of the logos in a grid, and get rid of the builder locations~~
2) Make the tabs a little smaller (fixed to a single row), display logos in each builder as a grid, and get rid of **just** the copy to clipboard button

**Comment by arjun024** [comment]
Shoulf be resolved by https://github.com/paketo-buildpacks/paketo-website/commit/6d0730d0fbd3152b66ebae627f1d0008ec3df1ce

**Comment by kvedurmu** [comment]
This looks great! Confirmed that the tabs for full, base, tiny are restricted to a single row, the logos are in a grid instead of row on mobile, and that the copy to clipboard button is removed. 
![image](https://user-images.githubusercontent.com/37810054/91331071-4c567080-e798-11ea-8c8c-973adc7bcaac.png)

**Comment by kvedurmu** [comment]
Actually. I'm going to open this back up. Now that I look at it a little closer, I think the logos could use a little more padding. For example, the node.js and PHP logos are really close to each other.

**Comment by kvedurmu** [comment]
Scratch that. We just discussed getting rid of the tab layout because it's difficult for new project users to understand, and will be moving back to the old logo view that we had before.
