### ISSUE TITLE
Implement Algolia search Detached Mode on Mobile

### ISSUE THREAD

**Issue by TisVictress** [paketo-buildpacks/paketo-website#336]
Algolia provides a Detached mode for DocSearch so that search results can be displayed in a full screen modal rather than a dropdown. This could enhance the user experience on mobile devices. Detached mode can be customized so that it's activated when the screen is a certain size using the [detachedMediaQuery](https://www.algolia.com/doc/ui-libraries/autocomplete/api-reference/autocomplete-js/autocomplete/#param-detachedmediaquery) option.

This story is to enable full screen detached mode for mobile only.

Currently, search results are displayed in a dropdown:
![Screen Shot 2021-10-05 at 6 03 09 PM](https://user-images.githubusercontent.com/29051306/136109035-542af8e9-68a1-44d9-8dbc-8d353fc9262a.png)

The search results on mobile should look something like this:
<img src="https://user-images.githubusercontent.com/29051306/136109245-4f5e6fdf-7bee-4f79-a39b-3d204825da39.png" width="800">

While searching, the contents of the website should not be visible.

More info can be found in the email forward by Frankie.

**Comment by fg-j** [comment]
This has been done in #426
