### ISSUE TITLE
SEO Updates for Paketo website

### ISSUE THREAD

**Issue by Superv0n** [paketo-buildpacks/paketo-website#368]
## Current state
When searching for Open Source Buildpacks on google (as an example), our Paketo website is displayed in results much farther down the list than it should. The words open source do not appear anywhere on our site. 

## Desired state
Our Paketo buildpacks are within a more reasonable position (based on index of course but we SHOULD be in the top 5) in search results with the proposed change
### Checklist
Details on the paketo.io page under this text is updated: The Paketo <**Open Source**> project provides production-ready buildpacks for the most popular languages and frameworks
"Open Source" is the new text to add.
- If you have any questions, please speak with the submitter.

**Comment by fg-j** [comment]
@Superv0n This seems like a great idea. For my own learning, how do you determine that "Our Paketo buildpacks are within a more reasonable position" with this change? Is there some SEO simulator you're using?

**Comment by Superv0n** [comment]
@fg-j I'm using Sitebulb to help determine our SEO indexing vs competitors. I can show you how to use this.
