### ISSUE TITLE
[Security] Workflow deploy-dev-pr.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Ale0x78** [paketo-buildpacks/paketo-website#382]
The workflow deploy-dev-pr.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by fg-j** [comment]
Hi. Thanks for bringing up your concern. However, I don't see the issue you're talking about. As far as I can see, the [current version](https://github.com/paketo-buildpacks/paketo-website/blob/be6f10a602397e17f39294bc98b655bac59209dc/.github/workflows/deploy-dev-pr.yml) of the deploy dev PR workflow is using [`actions/checkout v2.4.0`](https://github.com/paketo-buildpacks/paketo-website/blob/be6f10a602397e17f39294bc98b655bac59209dc/.github/workflows/deploy-dev-pr.yml#L19).

It appears that v2.4.0 contains the referenced commit. (See [commit view](https://github.com/actions/checkout/commit/a6747255bd19d7a757dbdda8c654a9f84db19839))
![image](https://user-images.githubusercontent.com/21328286/146796624-c16b7d40-6f70-4656-bec1-080739165d0f.png)

Did something else give you reason to believe that we are using a vulnerable version of this action?
