### ISSUE TITLE
Add Python SBOM docs

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/paketo-website#474]
## Problem

Recently Syft-supported SBOMs have been getting added to Paketo Python CNBs as a part of https://github.com/paketo-buildpacks/python/issues/399.

Once this is done and released, we should add information to the Python docs to mention SBOM availability, as well as any caveats (for example, the SBOM is only present for Conda Env Update CNB build process if the app is vendored, or in cases where there's a lockfile).

The Node documentation has something like this in the reference section: https://paketo.io/docs/reference/nodejs-reference/#software-bill-of-materials, but I also think we should mention it in the How-To section if possible!

### Affected page(s)

- Python docs 

### Checklist
- [ ] I have included links to page(s) that need to be changed

**Comment by sophiewigmore** [comment]
Blocked on completion of linked Python issue to implement SBOM.

**Comment by fg-j** [comment]
These docs should include any caveats about python SBOM support depending on package managers.
