### ISSUE TITLE
Document extending the builder

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/paketo-website#476]
## Problem

I want to add some extra stuff to the existing builder and I'm not sure how. We should document that you can modify the builder by doing something like what is outlined in these docs: https://github.com/GoogleCloudPlatform/buildpacks/tree/249967b33d5c3727df311b1beeecc0df379bb1b4#extending-the-builder-image.

### Affected page(s)

- https://paketo.io/docs/concepts/builders/

### Checklist
- [x] I have included links to page(s) that need to be changed

**Comment by fg-j** [comment]
I'd be in favor of creating a How To page for builders to hold this content.
