### ISSUE TITLE
Inaugural blog post living ouside blog.paketo.io

### ISSUE THREAD

**Issue by davidmirror-ops** [paketo-buildpacks/paketo-website#492]
## Current state
A [blog post](https://medium.com/paketo-buildpacks/building-apps-for-kubernetes-get-to-know-paketo-buildpacks-6dc29b0f3cf3) demonstrating and describing the value proposition of the project is residing under the Paketo Buildpacks space on Medium.

## Desired state
First post at blog.paketo.io should be the one announcing/introducing the project. In this case, the decisions to be discussed are:

1. Is [this post](https://medium.com/paketo-buildpacks/building-apps-for-kubernetes-get-to-know-paketo-buildpacks-6dc29b0f3cf3) available (mostly in terms of IP/copyright/etc) to be migrated over to blog.paketo.io?
2. Is the goal to keep posting at both sites? (blog.paketo.io and Medium)

**Comment by fg-j** [comment]
My understanding was we moved off Medium since they implemented a paywall and we didn't want our content stuck behind one. Kashyap (blog post author) is no longer involved with the project, so I'm not sure what the IP policy is around that.

**Comment by davidmirror-ops** [comment]
Just realized that the post is already in the Paketo site

https://blog.paketo.io/posts/get-to-know-paketo-buildpacks/
