### ISSUE TITLE
Improve typography and colors

### ISSUE THREAD

**Issue by sampeinado** [paketo-buildpacks/paketo-website#52]
I have made a [mockup in Figma](https://www.figma.com/file/Jxx4YFb2d1cD718KrhCrnk/Paketo.io?node-id=63%3A223) which shows a set of typography and color changes for the homepage. These can also be applied to the docs pages. The relevant page is "Handoff Spec 10/1/20." When you click on the "Comments" icon in the top navbar, you can see a list of the specified changes.  

Please reach out when you are ready to work on this so that I can give a short walkthrough of the changes and how to use Figma to copy some of the CSS directly!

Caveat: I know that this mockup doesn't fully reflect the new "copy-paste" feature that is in staging, but I don't think any of the changes should be in conflict with that change. Please reach out if there are any conflicts and we can talk through it together.

New assets attached:
[Assets.zip](https://github.com/paketo-buildpacks/paketo-website/files/5312810/Assets.zip)

Preview:
![Paketo Home](https://user-images.githubusercontent.com/35495560/94823862-56d8db00-03d2-11eb-86ca-76bb278ca759.png)

**Comment by kvedurmu** [comment]
This color scheme and typography change looks good to me. @sampeinado would the background color scheme changes apply to the rest of the website as well? All of the docs pages still have the grey background. I don't have any strong opinions, but we should just make sure it's consistent.

**Comment by sampeinado** [comment]
yes the intention is that they should apply to the rest of the website as well
