### ISSUE TITLE
Improve Docs Menu Typography and Hover States 

### ISSUE THREAD

**Issue by sampeinado** [paketo-buildpacks/paketo-website#60]
I have made a [mockup in Figma](https://www.figma.com/file/Jxx4YFb2d1cD718KrhCrnk/Paketo.io?node-id=63%3A223) which shows a set of docs background color, docs menu typography, and hover state changes. The relevant page is "Handoff Spec 10/1/20" and you can look at the frames "Docs Page 10/12/20," "Docs Left Menu Hover State," and "Links Hover State" for the new changes. When you click on the "Comments" icon in the top navbar, you can see a list of the specified changes. This issue deals with Comments 14 and 17-24.

**Comment by ForestEckhardt** [comment]
A quick summary of the changes above for those unable to access the Figma:
- [ ] Fix font color change when hovering on \<a\>
- [ ] Change the background color to white (#FEFEFE) for docs page
- [ ] Change sidebar and header color light blue (#EFF2F8) for docs page 
- [ ] Turn `Getting Started` link into a button that says `Getting Started`
- [ ] Turn “What are Buildpacks” and “Why Paketo Buildpacks” into \<h1\> from \<h2\> 
- [ ] Change \<h2\> to be 400 weight 
- [ ] Change \<body\> to be 400 wieght
- [ ] Change \<h1\> to be 600 weight 
- [ ] Change \<h4\> to have new style according to 
```
{
font-weight: bold;
font-size: 19px;
line-height: 23px;
letter-spacing: 0.05em;
color: #4A516D;
}
```
- [ ] Change \<a\> hover color of docs sidebar for bright blue (#5DBCD2)
- [ ] Add hover to code output button to change cursor to `pointer`
- [ ] Sub docs menu items should have less font weight then the top level items
