### ISSUE TITLE
Add a Paketo Buildpack Code Style Guide

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/paketo-website#8]
**Context**
We should create some sort of code style guide so that it's easy for new community members to pick up on Paketo Buildpacks development best practices and so long term maintenance of these buildpacks isn't cumbersome. 

**Proposal**
A code/development best practices styleguide that goes on the Paketo Website. There's still a question of where on the docs page this lives.

**Comment by ryanmoran** [comment]
Related: https://github.com/paketo-buildpacks/rfcs/pull/21

**Comment by kvedurmu** [comment]
If the styleguide eventually lives in the community repo we can probably close this, and figure out how to surface this guide as a part of https://github.com/paketo-buildpacks/paketo-website/issues/21

**Comment by kvedurmu** [comment]
@ForestEckhardt do you think we could close this one out since we have a styleguide [here](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md)?

**Comment by ryanmoran** [comment]
Bump @ForestEckhardt

**Comment by ForestEckhardt** [comment]
@kvedurmu I think that we should link to the style guid somewhere on the Contribute page on the website. Other than that I think that doc will do.

**Comment by fg-j** [comment]
@ForestEckhardt I'd like to close this out if possible. Do you still feel strongly about surfacing the code style guide on the website's contribute page?

**Comment by ForestEckhardt** [comment]
I do not feel strongly will close
