### ISSUE TITLE
Self-nomination as Paketo Website contributor

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/paketo-website#82]
In keeping with the Paketo Buildpacks Governance document, I am self-nominating as a contributor to the Paketo Website/content repositories.

I have contributes to different docs pages and formatting files over time, and most recently [submitted a PR](https://github.com/paketo-buildpacks/paketo-website/pull/81) to update Ruby buildpack docs.

**Comment by sophiewigmore** [comment]
@ForestEckhardt @kvedurmu any updates here? As well as on #83

**Comment by ForestEckhardt** [comment]
@sophiewigmore the nomination has been approved by a supermajority of maintainers. You will be added a contributor ASAP!
