### ISSUE TITLE
Nomination of @fg-j as a contributor

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/paketo-website#83]
In keeping with the Paketo Buildpacks Governance document, I am nominating @fg-j as a contributor to the Paketo Website/content repositories.

@fg-j has contributed to different docs pages and formatting files over time, for example [adding answers](https://github.com/paketo-buildpacks/paketo-website/commit/e6410dcf7ed2eeed5b91972aad4ad70ee605accc) to a number of FAQs on the website.

**Comment by fg-j** [comment]
@ForestEckhardt @kvedurmu bumping this thread

**Comment by ForestEckhardt** [comment]
We have reached a super majority. Congrats to @fg-j, we will get you add as a contributor ASAP!
