### ISSUE TITLE
Add anchor links to the documentation subheaders

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/paketo-website#91]
## What happened?

* What were you attempting to do?
  I wanted to link to a subsection in the docs and could not because those headers don't have anchor tags.

* What did you expect to happen?
  I expected there to be an anchor I could link to.

**Comment by fg-j** [comment]
This has been addressed. Check out, for instance: https://paketo.io/docs/howto/dotnet-core/#build-a-sample-app
