### ISSUE TITLE
Document how to use JVM distros other than Bellsoft Liberica 

### ISSUE THREAD

**Issue by ekcasey** [paketo-buildpacks/paketo-website#93]
Document how to use our additional JVM distro buildpacks. https://github.com/paketo-buildpacks/java/issues/87#issuecomment-769142584

**Comment by kvedurmu** [comment]
Thanks for creating this. I think what would be helpful on this doc is a list of all supported JVM distributions with links to them,  and how to create a builder/meta buildpack that pulls in this JVM distribution. 

Perhaps a follow-up to this could be a tutorial around how to use the libjvm library to create a JVM distro buildpack that's not currently supported.
